### PR TITLE
Extract librarian-chef into its own project

### PR DESCRIPTION
**Pull request by patcon**
I know it's not a novel idea, but just wanted to create this stub to discuss a timeline or goals we want to hit before that happens. Thanks!

Related: garethr/librarian-puppet-vagrant#1

### CODE REVIEW

**Comment by patcon** [comment]
I hope this was helpful and not too forward of me, but I extract it out to see if I could get it to work:
https://github.com/patcon/librarian-chef

Also created a gem namespace and made you the owner:
https://rubygems.org/gems/librarian-chef

Obviously, feel free to do anything you wish with that access, even delete the gem if you dislike the idea of it being present on rubygems.org :)

**Comment by patcon** [comment]
I was going to work at submitting a PR to librarian-puppet so that they can actually depend on the librarian framework. This is mostly out of being curious whether its workable for that project.

**Comment by yfeldblum** [comment]
@patcon Thanks for the PR.

I'm doing this separately in a branch because there are some cleanup-type things I'd like to do alongside the extraction.

I also want to alert others who do Chef-related projects that could break before releasing with `librarian-chef` extracted.

**Comment by patcon** [comment]
:+1:

In regards to keeping people updated, would it make sense to create a PR on the branch and cc all concerned parties into the developing thread? I know it wouldn't necessarily be much to code review, but might give people time to comment inline and in one place before you do the official presto-change-o

**Comment by patcon** [comment]
PS, came across [your old podcast](http://foodfightshow.org/2012/04/devops-delicacy-0-librarian-with-jay.html) last week, and interesting to hear the backstory. For the record, you don't sound nearly as unix-beardy as I'd expected

**Comment by yfeldblum** [comment]
Extracted.

Librarian-`v0.1.0.beta.1` released, sans Librarian-Chef.

**Comment by patcon** [comment]
Awesome! I think you tagged this as the wrong version, so it's showing as "yanked" on rubygems.org (since 0.0.26 is after 0.0.1):
https://rubygems.org/gems/librarian-chef

**Comment by yfeldblum** [comment]
AFAICT, there's a pre-release uploaded, but no release uploaded, so it's not showing any released versions.

You can still run:

```
gem install librarian-chef --pre
```

**Comment by gregkare** [comment]
You can close this one now that librarian-chef has been extracted and released.

**Comment by yfeldblum** [comment]
Indeed, thanks!

**Pull request closed without merging**
