### PR TITLE
Accommodate Bundler vendor everything users

### PR DESCRIPTION
**Pull request by taqtiqa-mark**
A common practice. More detail here http://ryan.mcgeary.org/2011/02/09/vendor-everything-still-applies/

### CODE REVIEW

**Comment by yfeldblum** [comment]
- How are you using bundler?
- Prefer to gitignore a specific set of subdirectories of `vendor`, rather than all of `vendor`.

**Comment by taqtiqa-mark** [comment]
Mostly as described in that blog entry.  Here is my `.bundle/config` :

```
---
BUNDLE_BIN: bin
BUNDLE_SHEBANG: ruby-local-exec
BUNDLE_DISABLE_SHARED_GEMS: '1'
BUNDLE_PATH: vendor
```

**Comment by yfeldblum** [comment]
I'd prefer to gitignore `vendor/cache` and `vendor/ruby`, since the `vendor` directory is also a conventional place for vendoring things that ought to be in source control (even though this project in particular doesn't have any such things yet).

**Comment by yfeldblum** [comment]
On second, though, it looks like Bundler moved their vendored copy of Thor into `lib/vendor/thor`.

**Pull request merged**
