### PR TITLE
GH-92: add http proxy support

### PR DESCRIPTION
**Pull request by tknerr**
adds proxy support along the same lines as in [rubygems](https://github.com/rubygems/rubygems/blob/v1.8.24/lib/rubygems/remote_fetcher.rb#L276-293) with `normalize(uri)` and `get_proxy_from_env()` methods copied over

### CODE REVIEW

**Comment by yfeldblum** [comment]
Is there a spec on `HTTP_PROXY` and friends?

**Comment by tknerr** [comment]
Nope, there were not, but now there are - thanks for the cleanup! :-)

**Comment by yfeldblum** [comment]
Heh, I meant, is there an RFC or other published document with which you're familiar, that explains in detail how programs should change their behaviors when `HTTP_PROXY` is given in the environment?

**Comment by tknerr** [comment]
Ah, I see :-)

Not that I'm aware of, but would be interested in that as well.

**Comment by proffalken** [comment]
Hi, are there any plans to update the gem currently found on rubygems.org? as far as I can tell this patch hasn't made it there yet... :(

**Comment by yfeldblum** [comment]
This is released in v0.0.25.

**Pull request merged**
